import type { LucideIcon } from "lucide-react";
import {
  // — currently used across the site content —
  Code2,
  Globe,
  Smartphone,
  ShoppingCart,
  PenTool,
  Share2,
  Megaphone,
  MonitorSmartphone,
  Network,
  Wifi,
  Lightbulb,
  Wrench,
  Boxes,
  Store,
  UtensilsCrossed,
  Building2,
  Briefcase,
  GraduationCap,
  HeartPulse,
  Landmark,
  HandHeart,
  Rocket,
  ShieldCheck,
  Gauge,
  Award,
  HeartHandshake,
  TrendingUp,
  Sparkles,
  Users,
  Target,
  LifeBuoy,
  Layers,
  // — extra choices for the admin icon picker —
  Cpu,
  Server,
  Database,
  Cloud,
  Laptop,
  Monitor,
  HardDrive,
  Router,
  Camera,
  Printer,
  Mail,
  Phone,
  MapPin,
  Clock,
  Settings,
  Cog,
  BarChart3,
  LineChart,
  PieChart,
  Activity,
  Zap,
  Bell,
  Calendar,
  CheckCircle2,
  Shield,
  Lock,
  Key,
  Wallet,
  CreditCard,
  DollarSign,
  ShoppingBag,
  Package,
  Truck,
  Bot,
  Palette,
  Image,
  Video,
  FileText,
  Folder,
  Search,
  Filter,
  Star,
  Heart,
  ThumbsUp,
  Trophy,
  Flag,
  Puzzle,
  Plug,
  Signal,
  Headphones,
  MessageSquare,
  Send,
  Link,
  Terminal,
  GitBranch,
  Building,
  Home,
  Factory,
  Stethoscope,
  BookOpen,
  User,
  UserCheck,
  Leaf,
  Sprout,
} from "lucide-react";

/**
 * The single source of truth mapping stored icon-name strings to Lucide
 * component references. Content in the database stores `icon` as one of these
 * keys; the read layer (lib/content.ts) resolves it back to a component, and
 * the admin icon picker offers exactly these choices.
 */
export const iconRegistry = {
  Code2,
  Globe,
  Smartphone,
  ShoppingCart,
  PenTool,
  Share2,
  Megaphone,
  MonitorSmartphone,
  Network,
  Wifi,
  Lightbulb,
  Wrench,
  Boxes,
  Store,
  UtensilsCrossed,
  Building2,
  Briefcase,
  GraduationCap,
  HeartPulse,
  Landmark,
  HandHeart,
  Rocket,
  ShieldCheck,
  Gauge,
  Award,
  HeartHandshake,
  TrendingUp,
  Sparkles,
  Users,
  Target,
  LifeBuoy,
  Layers,
  Cpu,
  Server,
  Database,
  Cloud,
  Laptop,
  Monitor,
  HardDrive,
  Router,
  Camera,
  Printer,
  Mail,
  Phone,
  MapPin,
  Clock,
  Settings,
  Cog,
  BarChart3,
  LineChart,
  PieChart,
  Activity,
  Zap,
  Bell,
  Calendar,
  CheckCircle2,
  Shield,
  Lock,
  Key,
  Wallet,
  CreditCard,
  DollarSign,
  ShoppingBag,
  Package,
  Truck,
  Bot,
  Palette,
  Image,
  Video,
  FileText,
  Folder,
  Search,
  Filter,
  Star,
  Heart,
  ThumbsUp,
  Trophy,
  Flag,
  Puzzle,
  Plug,
  Signal,
  Headphones,
  MessageSquare,
  Send,
  Link,
  Terminal,
  GitBranch,
  Building,
  Home,
  Factory,
  Stethoscope,
  BookOpen,
  User,
  UserCheck,
  Leaf,
  Sprout,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof iconRegistry;

/** Sorted list of icon names for the admin picker. */
export const iconNames = Object.keys(iconRegistry).sort() as IconName[];

/** Fallback used when a stored name is missing from the registry. */
export const FALLBACK_ICON: LucideIcon = Sparkles;

/** Resolve a stored icon-name string to a Lucide component (never throws). */
export function resolveIcon(name: string | null | undefined): LucideIcon {
  if (name && name in iconRegistry) {
    return iconRegistry[name as IconName];
  }
  return FALLBACK_ICON;
}

/** True when the given string is a valid registry key. */
export function isIconName(name: string): name is IconName {
  return name in iconRegistry;
}
