/**
 * One-off: emit a plain-SQL seed file (boj-seed.sql) equivalent to `npm run db:seed`
 * plus the admin user, for environments where the Prisma engine can't run
 * (e.g. CloudLinux shared hosting). Load it with the mysql client:
 *   mysql -u USER -pPASS DBNAME < boj-seed.sql
 */
import { writeFileSync } from "fs";
import { randomUUID } from "crypto";
import bcrypt from "bcryptjs";
import type { LucideIcon } from "lucide-react";
import { iconRegistry } from "../lib/icons";
import { services } from "../data/services";
import { solutions } from "../data/solutions";
import { projects } from "../data/portfolio";
import { industries } from "../data/industries";
import { site, socials, coreValues, whyChoose, stats } from "../data/site";

const ADMIN = {
  name: "bojtech",
  email: "admin@bojtechnologies.com",
  password: "n2c5c4.Ke.bojtech",
  role: "ADMIN",
};

const iconToName = new Map<LucideIcon, string>();
for (const [name, comp] of Object.entries(iconRegistry)) iconToName.set(comp as LucideIcon, name);
function iconName(icon: LucideIcon): string {
  const n = iconToName.get(icon);
  if (!n) throw new Error("Seed: icon missing from lib/icons.ts iconRegistry.");
  return n;
}

// MySQL string-literal escaping (backslash mode on by default).
function q(v: string | null | undefined): string {
  if (v === null || v === undefined) return "NULL";
  return (
    "'" +
    String(v)
      .replace(/\\/g, "\\\\")
      .replace(/'/g, "\\'")
      .replace(/\n/g, "\\n")
      .replace(/\r/g, "\\r") +
    "'"
  );
}
const j = (v: unknown) => q(JSON.stringify(v));
const NOW = "NOW(3)";

const out: string[] = [];
out.push("-- Generated by scripts/gen-seed-sql.ts — mirrors `npm run db:seed` + admin user.");
out.push("SET NAMES utf8mb4;");
out.push("START TRANSACTION;");

out.push("\nDELETE FROM `Service`;");
services.forEach((s, i) => {
  out.push(
    "INSERT INTO `Service` (`slug`,`name`,`shortName`,`tagline`,`icon`,`shortDescription`,`overview`,`features`,`outcomes`,`image`,`imageAlt`,`imagePlaceholder`,`imageCategory`,`order`,`updatedAt`) VALUES (" +
      [q(s.slug), q(s.name), q(s.shortName), q(s.tagline), q(iconName(s.icon)), q(s.shortDescription), q(s.overview), j(s.features), j(s.outcomes), q(s.image ?? null), q(s.imageAlt), q(s.imagePlaceholder), q(s.imageCategory), i, NOW].join(",") +
      ");"
  );
});

out.push("\nDELETE FROM `Solution`;");
solutions.forEach((s, i) => {
  out.push(
    "INSERT INTO `Solution` (`slug`,`name`,`category`,`tagline`,`icon`,`description`,`highlights`,`status`,`accent`,`image`,`imageAlt`,`imagePlaceholder`,`imageCategory`,`order`,`updatedAt`) VALUES (" +
      [q(s.slug), q(s.name), q(s.category), q(s.tagline), q(iconName(s.icon)), q(s.description), j(s.highlights), q(s.status), q(s.accent), q(s.image ?? null), q(s.imageAlt), q(s.imagePlaceholder), q(s.imageCategory), i, NOW].join(",") +
      ");"
  );
});

out.push("\nDELETE FROM `Project`;");
projects.forEach((p, i) => {
  out.push(
    "INSERT INTO `Project` (`slug`,`name`,`category`,`client`,`year`,`description`,`tags`,`image`,`imageAlt`,`imagePlaceholder`,`imageCategory`,`order`,`updatedAt`) VALUES (" +
      [q(p.slug), q(p.name), q(p.category), q(p.client), q(p.year), q(p.description), j(p.tags), q(p.image ?? null), q(p.imageAlt), q(p.imagePlaceholder), q(p.imageCategory), i, NOW].join(",") +
      ");"
  );
});

out.push("\nDELETE FROM `Industry`;");
industries.forEach((ind, i) => {
  out.push(
    "INSERT INTO `Industry` (`slug`,`name`,`icon`,`description`,`image`,`imageAlt`,`imagePlaceholder`,`imageCategory`,`order`,`updatedAt`) VALUES (" +
      [q(ind.slug), q(ind.name), q(iconName(ind.icon)), q(ind.description), q(ind.image ?? null), q(ind.imageAlt), q(ind.imagePlaceholder), q(ind.imageCategory), i, NOW].join(",") +
      ");"
  );
});

out.push("\nDELETE FROM `CoreValue`;");
coreValues.forEach((v, i) => {
  out.push(
    "INSERT INTO `CoreValue` (`title`,`description`,`icon`,`order`,`updatedAt`) VALUES (" +
      [q(v.title), q(v.description), q(iconName(v.icon)), i, NOW].join(",") +
      ");"
  );
});

out.push("\nDELETE FROM `WhyChoose`;");
whyChoose.forEach((w, i) => {
  out.push(
    "INSERT INTO `WhyChoose` (`title`,`description`,`icon`,`order`,`updatedAt`) VALUES (" +
      [q(w.title), q(w.description), q(iconName(w.icon)), i, NOW].join(",") +
      ");"
  );
});

out.push("\nDELETE FROM `Stat`;");
stats.forEach((st, i) => {
  out.push(
    "INSERT INTO `Stat` (`value`,`suffix`,`label`,`shortLabel`,`order`,`updatedAt`) VALUES (" +
      [q(st.value), q(st.suffix), q(st.label), q(st.shortLabel), i, NOW].join(",") +
      ");"
  );
});

out.push("\nDELETE FROM `SiteSetting`;");
out.push(
  "INSERT INTO `SiteSetting` (`id`,`name`,`shortName`,`legalName`,`tagline`,`description`,`longDescription`,`url`,`email`,`salesEmail`,`phonePrimary`,`phoneSecondary`,`location`,`addressLines`,`hours`,`socials`,`updatedAt`) VALUES (" +
    [1, q(site.name), q(site.shortName), q(site.legalName), q(site.tagline), q(site.description), q(site.longDescription), q(site.url), q(site.email), q(site.salesEmail), q(site.phonePrimary), q(site.phoneSecondary), q(site.location), j(site.addressLines), j(site.hours), j(socials), NOW].join(",") +
    ");"
);

const hash = bcrypt.hashSync(ADMIN.password, 12);
out.push("\nDELETE FROM `User` WHERE `email` = " + q(ADMIN.email) + ";");
out.push(
  "INSERT INTO `User` (`id`,`name`,`email`,`passwordHash`,`role`,`updatedAt`) VALUES (" +
    [q(randomUUID()), q(ADMIN.name), q(ADMIN.email), q(hash), q(ADMIN.role), NOW].join(",") +
    ");"
);

out.push("\nCOMMIT;");

writeFileSync("boj-seed.sql", out.join("\n") + "\n", "utf8");
console.log(
  `Wrote boj-seed.sql: ${services.length} services, ${solutions.length} solutions, ${projects.length} projects, ${industries.length} industries, ${coreValues.length} values, ${whyChoose.length} why-choose, ${stats.length} stats, 1 settings, 1 admin.`
);
